### ISSUE TITLE
ETH: Eth2MakerDaiDelegate Strategy

### ISSUE THREAD

**Issue by dougstorm** [iearn-finance/yearn-strategies#10]
Description: Port of the ETH v1 Strategy using Maker to mint DAI and invest in yvDAI vault.

Commit: [6d94f26cde7aa6dfbd7d7ddbf00bf2ec4fb6e7ea](https://github.com/orbxball/ethMKRVaultDAIDelegate/commit/6d94f26cde7aa6dfbd7d7ddbf00bf2ec4fb6e7ea)

Repo: [ethMKRVaultDAIDelegate](https://github.com/orbxball/ethMKRVaultDAIDelegate)

Review Completed By:

- [x] Doug

**Comment by dmolina79** [comment]
https://github.com/orbxball/ethMKRVaultDAIDelegate/blob/6d94f26cde7aa6dfbd7d7ddbf00bf2ec4fb6e7ea/contracts/Strategy.sol#L134

Not sure if this is needed, seems like the Base method would work just the same right?

https://github.com/iearn-finance/yearn-vaults/blob/7df3e77d6ae52f098e80f0fbc424f96473a2790c/contracts/BaseStrategy.sol#L460

**Comment by dmolina79** [comment]
Comment:

This is a minor suggestion in the constructor as an extra safety check that i have recommended to other strategist:
see
https://github.com/iearn-finance/yearn-strategies/issues/6#issuecomment-743690760

**Comment by dmolina79** [comment]
Question/suggestion:
Is it always guaranteed that this line will free the amount needed/requested? or does it need a return value if there is a difference?

https://github.com/orbxball/ethMKRVaultDAIDelegate/blob/6d94f26cde7aa6dfbd7d7ddbf00bf2ec4fb6e7ea/contracts/Strategy.sol#L317

Asking because i see the `_amountFreed = _amountNeeded` line after, so its assuming its safe to override the value without any additional check after the side effect

Not sure its possible to get the value of the actual amount freed or check before and after otherwise if it makes sense?

**Comment by orbxball** [comment]
> Not sure if this is needed, seems like the Base method would work just the same right?

Yes. It's the same.

> This is a minor suggestion in the constructor as an extra safety check that i have recommended to other strategist:

Nice check.

> Question/suggestion:
> Is it always guaranteed that this line will free the amount needed/requested? or does it need a return value if there is a difference?
> 
> Asking because i see the `_amountFreed = _amountNeeded` line after, so its assuming its safe to override the value without any additional check after the side effect
> 
> Not sure its possible to get the value of the actual amount freed or check before and after otherwise if it makes sense?

Yes. All the credit, want(weth), is always locked in Maker Vault, it doesn't go anywhere, different from lending. So it can always get the amount requested from the vault, unless the `_amountNeeded` is more than the credit it gets from the vault. But that would be a problem at vault side. It should not be handled at the strategy level. 

As for the side effect checking, there is actually an additional check, `withdrawDaiLeast`, to be as a second protection.
