### ISSUE TITLE
Review Sam's Iron Bank Alpha Lender

### ISSUE THREAD

**Issue by dougstorm** [iearn-finance/yearn-strategies#17]
Description: Lender that works with generic lender to iron bank

Initial Review Commit: [ab07bd8b9c3a7b74344accbf7e5d76fed752b728](https://github.com/Grandthrax/AlphaHomoV2EarnDeposit/commit/ab07bd8b9c3a7b74344accbf7e5d76fed752b728)

Latest Review Commit: [ab07bd8b9c3a7b74344accbf7e5d76fed752b728](https://github.com/Grandthrax/AlphaHomoV2EarnDeposit/commit/ab07bd8b9c3a7b74344accbf7e5d76fed752b728)

Repo: [Strategy.sol](https://github.com/Grandthrax/AlphaHomoV2EarnDeposit/blob/master/contracts/Strategy.sol)

Relevant code being used: 
https://github.com/AlphaFinanceLab/homora-v2/blob/master/contracts/SafeBox.sol

Review Completed By:

- [x] Doug
- [x] Carlos
- [x] Andy
- [x] Doggie

**Comment by dougstorm** [comment]
Suggestion:

https://github.com/Grandthrax/AlphaHomoV2EarnDeposit/blob/ab07bd8b9c3a7b74344accbf7e5d76fed752b728/contracts/Strategy.sol#L44

Add this check for vault too.

**Comment by dougstorm** [comment]
Comment:

Curious if there is a reason here we don't use the debt outstanding value provided? and instead we ask for vault.totalDebt?

https://github.com/Grandthrax/AlphaHomoV2EarnDeposit/blob/ab07bd8b9c3a7b74344accbf7e5d76fed752b728/contracts/Strategy.sol#L109

Asking because in vault code this value already accounts for debtLimit and handles the emergency shutdown scenario here:

```
@view
@internal
def _debtOutstanding(strategy: address) -> uint256:
    # See note on `debtOutstanding()`.
    strategy_debtLimit: uint256 = self.strategies[strategy].debtRatio * self._totalAssets() / MAX_BPS
    strategy_totalDebt: uint256 = self.strategies[strategy].totalDebt

    if self.emergencyShutdown:
        return strategy_totalDebt
    elif strategy_totalDebt <= strategy_debtLimit:
        return 0
    else:
        return strategy_totalDebt - strategy_debtLimit
 ```

**Comment by Grandthrax** [comment]
> Suggestion:
> 
> https://github.com/Grandthrax/AlphaHomoV2EarnDeposit/blob/ab07bd8b9c3a7b74344accbf7e5d76fed752b728/contracts/Strategy.sol#L44
> 
> Add this check for vault too.

sure will add

**Comment by Grandthrax** [comment]
> Comment:
> 
> Curious if there is a reason here we don't use the debt outstanding value provided? and instead we ask for vault.totalDebt?

Debt outstanding is the amount the vault wants back (it is normally 0). totalDebt is the total amount the vault thinks we have. We use the later to work out our profit.

**Comment by dougstorm** [comment]
Suggestion:

Add to test the exact balance migrated in iron bank dai token instead of checking a value above zero for precision
https://github.com/Grandthrax/AlphaHomoV2EarnDeposit/blob/ab07bd8b9c3a7b74344accbf7e5d76fed752b728/tests/test_operation.py#L78

**Comment by Grandthrax** [comment]
> Suggestion:
> 
> Add to test the exact balance migrated in iron bank dai token instead of checking a value above zero for precision
> https://github.com/Grandthrax/AlphaHomoV2EarnDeposit/blob/ab07bd8b9c3a7b74344accbf7e5d76fed752b728/tests/test_operation.py#L78

added here https://github.com/Grandthrax/AlphaHomoV2EarnDeposit/commit/fdb8c52db4c7f933611d0c0368fe50999ee5a116
