### ISSUE TITLE
Review Curve ETH/sETH vault Zaps

### ISSUE THREAD

**Issue by matkam** [iearn-finance/yearn-strategies#18]
## Simple one sided zap

Github: https://github.com/matkam/yearn-strategies/blob/master/contracts/ZapYvecrv.sol
Deployed: https://etherscan.io/address/0x2777938e0a1c12bce97c9cc9b36e737c08519a2c#code

Note: Can be added to yearn.rocks until complex zap is available.

## More complex zap

Description:
1. Provides an estimate for LP tokens
2. Trade ETH for sUSD, then exchanging it for sETH
3. Zapping ETH + sETH into vault

Github: https://github.com/matkam/yearn-strategies/blob/master/contracts/ZapYvecrvSwapSusd.sol

See for issues with complex zap: https://hackmd.io/R0Fh0CyUQ_q2QgJ1BjyF-Q?view

**Comment by dougstorm** [comment]
is this the deployed contract for this?

https://etherscan.io/address/0x2777938e0a1c12bce97c9cc9b36e737c08519a2c

i think this review can be closed right?
