### ISSUE TITLE
Review Mushroom WBTC strategy

### ISSUE THREAD

**Issue by fameal** [iearn-finance/yearn-strategies#20]
Description: deposits WBTC into Mushroom Finance to get $MM and sell for $WBTC

Commit: [0581628f514da12024bc64fea352d84ac4919db1](https://github.com/mushroomsforest/brownie-strategy-mix/commit/0581628f514da12024bc64fea352d84ac4919db1)

Tag: []()

Repo: [Mushrooms](https://github.com/mushroomsforest/brownie-strategy-mix/tree/mushrooms)

Deployed Contract [0x96e16da0d19f7b07c88d14ce85597acb94679326](https://etherscan.io/address/0x96e16da0d19f7b07c88d14ce85597acb94679326#code)

**Comment by dougstorm** [comment]
Suggestion:

Not sure how likely this can be an actual scenario

But consider adding a check for total supply in case is 0
https://github.com/mushroomsforest/brownie-strategy-mix/blob/b9248cdb9eb18372b9cdd1f2f758b9ae7ab3d455/contracts/Strategy.sol#L357

This method is used to calculate TotalEstimatedAssets and if it reverts we cannot liquidate position.

**Comment by mushroomsforest** [comment]
> 
> 
> Suggestion:
> 
> Not sure how likely this can be an actual scenario
> 
> But consider adding a check for total supply in case is 0
> https://github.com/mushroomsforest/brownie-strategy-mix/blob/b9248cdb9eb18372b9cdd1f2f758b9ae7ab3d455/contracts/Strategy.sol#L357
> 
> This method is used to calculate TotalEstimatedAssets and if it reverts we cannot liquidate position.

Thanks @dougstorm for reviewing. 

For `mmVault.totalSupply()`, it is an standard [ERC20 (forked from yVault v1)](https://etherscan.io/address/0xb06661A221Ab2Ec615531f9632D6Dc5D2984179A#code), I would say it is almost impossible equal to zero if this strategy still got some position in there. 

Even if some extreme situation like `totalSupply()` equals to zero happen(although I could not imagine how), we could still remedy the situation by manually deposit a satoshi of WBTC into `mmVault` to make the `totalSupply()` bigger than zero.

**Comment by mushroomsforest** [comment]
> 
> 
> > Suggestion:
> > Not sure how likely this can be an actual scenario
> > But consider adding a check for total supply in case is 0
> > https://github.com/mushroomsforest/brownie-strategy-mix/blob/b9248cdb9eb18372b9cdd1f2f758b9ae7ab3d455/contracts/Strategy.sol#L357
> > This method is used to calculate TotalEstimatedAssets and if it reverts we cannot liquidate position.
> 
> Thanks @dougstorm for reviewing.
> 
> For `mmVault.totalSupply()`, it is an standard [ERC20 (forked from yVault v1)](https://etherscan.io/address/0xb06661A221Ab2Ec615531f9632D6Dc5D2984179A#code), I would say it is almost impossible equal to zero if this strategy still got some position in there.
> 
> Even if some extreme situation like `totalSupply()` equals to zero happen(although I could not imagine how), we could still remedy the situation by manually deposit a satoshi of WBTC into `mmVault` to make the `totalSupply()` bigger than zero.

fixed in this commit: https://github.com/mushroomsforest/brownie-strategy-mix/commit/3d3cb345c54f8985021d5cdf46d8458536d33e76 Thanks

**Comment by dougstorm** [comment]
> `mmVault` to make the `totalSupply()` bigger than zero.

Agree, highly unlikely, reviewed latest changes and looks good
