### ISSUE TITLE
Sam's Iron Bank Strat

### ISSUE THREAD

**Issue by dougstorm** [iearn-finance/yearn-strategies#24]
Description: Sam's Iron Bank Strategy

Initial Commit: [d1efe916784c3070da30153681afbf2132770423](https://github.com/Grandthrax/iron-bank-comp-strat/commit/d1efe916784c3070da30153681afbf2132770423)

Latest Commit After Review: [d1efe916784c3070da30153681afbf2132770423](https://github.com/Grandthrax/iron-bank-comp-strat/commit/d1efe916784c3070da30153681afbf2132770423)

Tag: []()

Repo: [Strategy](https://github.com/Grandthrax/iron-bank-comp-strat/blob/master/contracts/Strategy.sol)

Deployed Contract [TBD](TBD)

Review Ongoing By:

- [x] Doug

Review Completed By:

- [x] Doug
- [x ] Poolpi

**Comment by dougstorm** [comment]
Suggestions on using Modifiers on all setters:


Both modifiers are already available from BaseStrategy so no need to add these
onlyAuthorized and onlyGovernance

https://github.com/Grandthrax/iron-bank-comp-strat/blob/fbd1724d533271a271702c85a6419caa30bc07c5/contracts/Strategy.sol#L100

Also all setters can use the modifiers instead of the local required

https://github.com/Grandthrax/iron-bank-comp-strat/blob/fbd1724d533271a271702c85a6419caa30bc07c5/contracts/Strategy.sol#L110

**Comment by dougstorm** [comment]
Question:

Does `getLivePosition`  need to be public?

https://github.com/Grandthrax/iron-bank-comp-strat/blob/fbd1724d533271a271702c85a6419caa30bc07c5/contracts/Strategy.sol#L531

Can you explain a bit more why it is state changing on the underlying protocols?

**Comment by dougstorm** [comment]
Suggestion:

Make the field values public so they can show up on etherscan since its easier for users to verify

https://github.com/Grandthrax/iron-bank-comp-strat/blob/fbd1724d533271a271702c85a6419caa30bc07c5/contracts/Strategy.sol#L33

**Comment by dougstorm** [comment]
Suggestion:

can cleanup unused code
https://github.com/Grandthrax/iron-bank-comp-strat/blob/fbd1724d533271a271702c85a6419caa30bc07c5/contracts/Strategy.sol#L169

**Comment by Grandthrax** [comment]
> Suggestions on using Modifiers on all setters:

I would like to but not enough space :(

**Comment by Grandthrax** [comment]
> Can you explain a bit more why it is state changing on the underlying protocols?

To get the accurate borrow balance accrueInterest needs to be run on ctoken which is state changing. getCurrentPosition is non state changing and gets the position at the last time someone called accrueInterest

**Comment by dougstorm** [comment]
Suggestion:

Another cleanup

https://github.com/Grandthrax/iron-bank-comp-strat/blob/d38f882432249a391c422bf3592565b33ac4ef61/contracts/Strategy.sol#L667

**Comment by dougstorm** [comment]
> > Suggestions on using Modifiers on all setters:
> 
> I would like to but not enough space :(

ok didnt know that about space, i guess its a nice to have but we can deploy and later look to optimize, not a security concern since all helpers do the security checks

**Comment by dougstorm** [comment]
Comment:

https://github.com/Grandthrax/iron-bank-comp-strat/blob/d38f882432249a391c422bf3592565b33ac4ef61/contracts/Strategy.sol#L269

We are aware that this calculations for creditOfficer are expensive, maybe some of this can be pre calculated and cache before, or add a gasToken support to help in harvests. 

All changes we can optimize in later versions

**Comment by Grandthrax** [comment]
Suggested changes here:
https://github.com/Grandthrax/iron-bank-comp-strat/commit/2227acc5f7a7d06e11902614a9c1e3b5d7a29c07

**Comment by Grandthrax** [comment]
https://github.com/Grandthrax/iron-bank-comp-strat/commit/d1efe916784c3070da30153681afbf2132770423

**Comment by dougstorm** [comment]
Update reviewed here: 

https://github.com/Grandthrax/iron-bank-comp-strat/commit/88b5c405ad90e7cd4ebb386b7d3108853a6032d6

Looks good, required small change to support new change from IB
