### ISSUE TITLE
Zap for yveCRV backscratcher and pickle

### ISSUE THREAD

**Issue by dougstorm** [iearn-finance/yearn-strategies#26]
https://github.com/TheRyanMiller/Zap-SLP-YVECRV-ETH

Description: Zap for SLP yveCRV ETH

Commit: [bfcbdd2d7f3fd1804b09b6dae0fce10f1e459341](https://github.com/TheRyanMiller/Zap-SLP-YVECRV-ETH/commit/bfcbdd2d7f3fd1804b09b6dae0fce10f1e459341)

Latest Commit after review: [0217105135381f07f2f4ebcccac8d9dc6d26d35c](https://github.com/TheRyanMiller/Zap-SLP-YVECRV-ETH/commit/0217105135381f07f2f4ebcccac8d9dc6d26d35c)

Tag:

Repo: https://github.com/TheRyanMiller/Zap-SLP-YVECRV-ETH

Scope: (List link to files)
[ZapYveCrvEthLPsToPickle.sol](https://github.com/TheRyanMiller/Zap-SLP-YVECRV-ETH/blob/master/contracts/ZapYveCrvEthLPsToPickle.sol)

Additional References or Repo (Link to underlying protocols or relevant documents)

Deployed Contract TBD

Review Ongoing By:

- [x] Doug

Review Completed By:

- [x] Doug

**Comment by dougstorm** [comment]
Suggestion:

https://github.com/TheRyanMiller/Zap-SLP-YVECRV-ETH/blob/bfcbdd2d7f3fd1804b09b6dae0fce10f1e459341/contracts/ZapYveCrvEthLPsToPickle.sol#L42

make all contract dependencies public for verification.

**Comment by dougstorm** [comment]
Question:

Can we leave immutable the pairs for each dex instead of passing it?
https://github.com/TheRyanMiller/Zap-SLP-YVECRV-ETH/blob/bfcbdd2d7f3fd1804b09b6dae0fce10f1e459341/contracts/ZapYveCrvEthLPsToPickle.sol#L182

If the pairs are know for sushi and Uni do we need to handle other pairs?

**Comment by dougstorm** [comment]
Suggestion:

Do we want to make the fallback function accept ETH deposits like yWETH vault here:

https://github.com/iearn-finance/yearn-protocol/blob/5bed056b390cf94342114db26dc8a8ab5bfb61de/contracts/vaults/yWETH.sol#L167

**Comment by dougstorm** [comment]
Suggestion:

Can you add comment the link reference for the magic numbers like here:
https://github.com/TheRyanMiller/Zap-SLP-YVECRV-ETH/blob/bfcbdd2d7f3fd1804b09b6dae0fce10f1e459341/contracts/ZapYveCrvEthLPsToPickle.sol#L206

And here a comment: 

https://github.com/TheRyanMiller/Zap-SLP-YVECRV-ETH/blob/bfcbdd2d7f3fd1804b09b6dae0fce10f1e459341/contracts/ZapYveCrvEthLPsToPickle.sol#L241

**Comment by dougstorm** [comment]
suggestion:

invert arguments to keep it cohesive with other methods or do boolean as last argument on all methods

https://github.com/TheRyanMiller/Zap-SLP-YVECRV-ETH/blob/bfcbdd2d7f3fd1804b09b6dae0fce10f1e459341/contracts/ZapYveCrvEthLPsToPickle.sol#L162

**Comment by dougstorm** [comment]
Suggestion:

change to send to governance address for consistency

https://github.com/TheRyanMiller/Zap-SLP-YVECRV-ETH/blob/bfcbdd2d7f3fd1804b09b6dae0fce10f1e459341/contracts/ZapYveCrvEthLPsToPickle.sol#L190

**Comment by dougstorm** [comment]
Small Optimization:

i think this can be defaulted without = false and it still false and it adds a small gas saving

https://github.com/TheRyanMiller/Zap-SLP-YVECRV-ETH/blob/bfcbdd2d7f3fd1804b09b6dae0fce10f1e459341/contracts/ZapYveCrvEthLPsToPickle.sol#L59

**Comment by dougstorm** [comment]
Issue:

Should we revert here?

https://github.com/TheRyanMiller/Zap-SLP-YVECRV-ETH/blob/bfcbdd2d7f3fd1804b09b6dae0fce10f1e459341/contracts/ZapYveCrvEthLPsToPickle.sol#L121

**Comment by dougstorm** [comment]
Suggestion:

could this be refactor to a modifier somehow?

https://github.com/TheRyanMiller/Zap-SLP-YVECRV-ETH/blob/bfcbdd2d7f3fd1804b09b6dae0fce10f1e459341/contracts/ZapYveCrvEthLPsToPickle.sol#L159

Otherwise maybe moving line 
` reEntry = false;`
to same scope visibility as the turning on of the flag could be an option.

```

function zapInETH() external payable {
        // When reEntry = trueAllow, only allow ETH from DEX routers
        if (reEntry && msg.sender != activeDex && msg.sender != sushiswapRouter) {
            require(msg.value == 0, "No re-entrancy!");
        }
        if(msg.sender != activeDex && msg.sender != sushiswapRouter){
            reEntry = true;
            _zapIn(true, msg.value);
            reEntry = false;
        }
    }
    ```

**Comment by dougstorm** [comment]
Comment:

Im not 100% sure

https://github.com/TheRyanMiller/Zap-SLP-YVECRV-ETH/blob/bfcbdd2d7f3fd1804b09b6dae0fce10f1e459341/contracts/ZapYveCrvEthLPsToPickle.sol#L108

But i think its highly unlikely we will ever run into a possible reentrancy issue since the dexes and addresses are immutable or know and also this contract is not meant to have balance at any point in time.

Also only instance when we handle native ETH transfers is on `sweep` function, if we switch governance address as suggested above shouldnt be an issue.

May be just a nitpick but also don't see the code doing any harm on extra precautions

**Comment by TheRyanMiller** [comment]
All updates are complete.
I've removed all the re-entrancy logic since it should not be needed in this contract which holds no ETH / token balance. 
In doing so, will ignore the following comments:

- https://github.com/iearn-finance/yearn-strategies/issues/26#issuecomment-783563835
- https://github.com/iearn-finance/yearn-strategies/issues/26#issuecomment-783565847
- https://github.com/iearn-finance/yearn-strategies/issues/26#issuecomment-783568227

**Comment by dougstorm** [comment]
Suggestion:

Simplify and gas optimization by moving ETH native operations with Router into WETH,

https://github.com/TheRyanMiller/Zap-SLP-YVECRV-ETH/blob/bfcbdd2d7f3fd1804b09b6dae0fce10f1e459341/contracts/ZapYveCrvEthLPsToPickle.sol#L142

https://github.com/TheRyanMiller/Zap-SLP-YVECRV-ETH/blob/bfcbdd2d7f3fd1804b09b6dae0fce10f1e459341/contracts/ZapYveCrvEthLPsToPickle.sol#L151

Saves gas moving to wETH and also simplifies the fallback handling

**Comment by TheRyanMiller** [comment]
Thanks @dougstorm . I've completed these changes. CRV Zap-Ins are the only ones affected as they dealt with ETH that was wrapped/unwrapped more than one time.

Tests pass. All updates have been pushed.

**Comment by dougstorm** [comment]
Changes looked good. Closing review
