### ISSUE TITLE
Review Alchemix contracts

### ISSUE THREAD

**Issue by dougstorm** [iearn-finance/yearn-strategies#29]
Description: vaults v2 integration of alchemix contracts

Commit: [?]()

Tag:

Scope: (list of files to review?)

Repo: https://github.com/alchemix-finance/Alchemix-Main/tree/dev

Deployed Contract TBD

Reference [Paper on Alchemix](https://alchemix.fi/c93eab454c206f9e1f054c723911112f.pdf)

Review Ongoing By:
- [x] Doug

Review Completed By:
- [x] Doug

Note: review was not extensive. Focused mainly on two components of the system that integrate yearn:
-YearnVaultAdapter.sol
-Alchemist.sol

Summary: could not find any major issues in code base for these components regarding yearn integrations

**Comment by thetechnocratic** [comment]
the latest contracts can be found on the #dev branch. after a conversation w/ Andre we have decided to remove the yAffiliateTokenV2, since our YearnVaultAdaptor performs a similar function.

**Comment by dougstorm** [comment]
Note: review was not extensive. Focused mainly on two components of the system that integrate yearn:
-YearnVaultAdapter.sol
-Alchemist.sol

Summary: could not find any major issues in code base for these components regarding yearn integrations
