### ISSUE TITLE
WETH: Generic Lender (Cream, dydx, compound and alpha homo)

### ISSUE THREAD

**Issue by dougstorm** [iearn-finance/yearn-strategies#5]
Description: Sam's Strategy for generic lending abstracting away lending protocols.

![Screen Shot 2020-12-10 at 14 41 49](https://user-images.githubusercontent.com/6074987/101827481-fcf14180-3af5-11eb-9387-dcb0845731f3.png)

Commit: [8488418e61fe21fba15187e0799d94531ed5cf8f](https://github.com/Grandthrax/yearnV2-generic-lender-strat/commit/8488418e61fe21fba15187e0799d94531ed5cf8f)

Latest Commit: [5659e4996251383c0198a6ca3c1084a6ef58c758](https://github.com/Grandthrax/yearnV2-generic-lender-strat/commit/5659e4996251383c0198a6ca3c1084a6ef58c758)

Tag: [0.2.2](https://github.com/Grandthrax/yearnV2-generic-lender-strat/releases/tag/0.2.2)

Repo: [Issues](https://github.com/Grandthrax/yearnV2-generic-lender-strat/issues)

Deployed latest Strategy:[0x460612682cE6ED51C1A9813F6938671D9D135d6D](https://etherscan.io/address/0x460612682cE6ED51C1A9813F6938671D9D135d6D#code)

Deployed Lender: [0x74bE25172F8aFFF92CA6e27418d601D74ACC2525](https://etherscan.io/address/0x74bE25172F8aFFF92CA6e27418d601D74ACC2525#code)

Scope of files reviewed:
[Strategy.sol](https://github.com/Grandthrax/yearnV2-generic-lender-strat/blob/0.2.2/contracts/Strategy.sol)
[AlphaHomoraLender.sol](https://github.com/Grandthrax/yearnV2-generic-lender-strat/blob/0.2.2/contracts/GenericLender/AlphaHomoLender.sol)
[GenericLenderBase.sol](https://github.com/Grandthrax/yearnV2-generic-lender-strat/blob/0.2.2/contracts/GenericLender/GenericLenderBase.sol)
[EthToEthOracle.sol](https://github.com/Grandthrax/yearnV2-generic-lender-strat/blob/0.2.2/contracts/WantToEthOracle/EthToEthOracle.sol)

Note Summary :
Other contract outside scope where not reviewed since we prioritized the deployed contracts in live testing first.
Other files can be added for review as we prepare to test them live.

TODO: waiting for audit

**Comment by Grandthrax** [comment]
> Description: Sam's Strategy for generic lending abstracting away lending protocols.
> 
> ![Screen Shot 2020-12-10 at 14 41 49](https://user-images.githubusercontent.com/6074987/101827481-fcf14180-3af5-11eb-9387-dcb0845731f3.png)


FYI this includes some stuff that isn't in this repo. It is to give an idea of how it fits overall. lev comp farm and maker del strat are different strategies.

**Comment by dmolina79** [comment]
Suggestion:
Can save some code by reusing this existing modifier from BaseStrategy:
https://github.com/iearn-finance/yearn-vaults/blob/c27ada2fe2b45fccc1dbbe251556a4738fbd4711/contracts/BaseStrategy.sol#L190


since its the same function as this modifier
https://github.com/Grandthrax/yearnV2-generic-lender-strat/blob/8488418e61fe21fba15187e0799d94531ed5cf8f/contracts/Strategy.sol#L580

**Comment by dmolina79** [comment]
Suggestion (Low Priority):

Copying the same suggestion that we applied to IDLE strat, if there is a way to validate the want token we are working with in the vault to avoid incorrect deployments.

See suggestion:

https://github.com/iearn-finance/yearn-strategies/issues/6#issuecomment-743690760

**Comment by dmolina79** [comment]
Suggestion (Low Priority):

Can save some gas here using a mapping `address => bool` if lender already exists we don't need a loop, we just add to the array. Altho this will also affect removal logic

https://github.com/Grandthrax/yearnV2-generic-lender-strat/blob/8488418e61fe21fba15187e0799d94531ed5cf8f/contracts/Strategy.sol#L68

**Comment by dmolina79** [comment]
Question:

Do we still want to reinvest even in a force withdrawal?

https://github.com/Grandthrax/yearnV2-generic-lender-strat/blob/8488418e61fe21fba15187e0799d94531ed5cf8f/contracts/Strategy.sol#L102

**Comment by dmolina79** [comment]
Comment:

Bit of an edge case but If this view method is called while the strategy has no lenders it returns the default values like lowestApr being the highest unsigned integer which not sure its correct.

https://github.com/Grandthrax/yearnV2-generic-lender-strat/blob/8488418e61fe21fba15187e0799d94531ed5cf8f/contracts/Strategy.sol#L239

**Comment by dmolina79** [comment]
Suggestion(medium):

Can expose in the GenericLender interface the strategy variable so it can be checked against when adding
here as an additional validation

https://github.com/Grandthrax/yearnV2-generic-lender-strat/blob/8488418e61fe21fba15187e0799d94531ed5cf8f/contracts/Strategy.sol#L66

```
require(n.strategy() == address(this)..);
```

**Comment by dmolina79** [comment]
Suggestion(critical):

Adding/removing lenders should be restricted only to governance, since these are contracts that handle the deposits they should be reviewed by core process before adding or removing to validate their safety.

https://github.com/Grandthrax/yearnV2-generic-lender-strat/blob/8488418e61fe21fba15187e0799d94531ed5cf8f/contracts/Strategy.sol#L65

**Comment by dmolina79** [comment]
Comment (Minor):

I think `_loss` always going to be 0 for this case, right?

https://github.com/Grandthrax/yearnV2-generic-lender-strat/blob/8488418e61fe21fba15187e0799d94531ed5cf8f/contracts/Strategy.sol#L346

**Comment by dmolina79** [comment]
Suggestion: (Medium)

Not 100% but `_withdrawSome()` could potentially not return the complete amount it can return.

Did a quick desk test with this data:

<img width="477" alt="Screen Shot 2020-12-17 at 16 14 53" src="https://user-images.githubusercontent.com/6074987/102550176-03963080-4083-11eb-89b7-a3948008cfc7.png">

https://github.com/Grandthrax/yearnV2-generic-lender-strat/blob/8488418e61fe21fba15187e0799d94531ed5cf8f/contracts/Strategy.sol#L459

Since the main check we do is with apr, we go thru the first lender the first time and withdraw 50 balance, 

lender 1 balance = 0 apr or something lower, 

i think we are never going to try withdrawing from the second lender.

Maybe a check of the apr + amount is more accurate?

**Comment by dmolina79** [comment]
Suggestion(Low):

Here:

https://github.com/Grandthrax/yearnV2-generic-lender-strat/blob/8488418e61fe21fba15187e0799d94531ed5cf8f/contracts/Strategy.sol#L456

Can consider only looping once thru lenders and asking for apr + amount to construct order of withdrawal once and then withdraw loop thru the order list.

**Comment by Grandthrax** [comment]
> Suggestion: (High)
> 
> I think `_withdrawSome()` could potentially not return the complete amount it can possibly return.
> 

We check if (lenders[i].hasAssets()) {

Does that not solve this problem?

So first iteration we withdraw from the lowest APR index 0. second iteration lowestAPR is reset. And now we check index 0 but as it has no assets we ignore it. Now index 1 has lowest APR.

**Comment by dmolina79** [comment]
> > Suggestion: (High)
> > I think `_withdrawSome()` could potentially not return the complete amount it can possibly return.
> 
> We check if (lenders[i].hasAssets()) {
> 
> Does that not solve this problem?
> 
> So first iteration we withdraw from the lowest APR index 0. second iteration lowestAPR is reset. And now we check index 0 but as it has no assets we ignore it. Now index 1 has lowest APR.

in that example i gave, `lowestApr` is never changed from the original 4% so we never update `lowest`  in line 461 since we never get into that condition or am i missing smth?

**Comment by Grandthrax** [comment]
> Suggestion(Low):
> 
> Here:
> 
> https://github.com/Grandthrax/yearnV2-generic-lender-strat/blob/8488418e61fe21fba15187e0799d94531ed5cf8f/contracts/Strategy.sol#L456
> 
> May save performance and gas if we have more than 3 lenders, can consider only looping once thru lenders and asking for apr + totalBalance to construct order of withdrawal once and then withdraw loop thru the order list.
> 
> It would be great to have the list preordered before withdraw transactions , in vaults we solved this with a queue for withdrawals order by priority in a secondary method.

this sounds useful but I don't really understand. can you elaborate?

**Comment by Grandthrax** [comment]
> Comment (Minor):
> 
> I think `_loss` always going to be 0 for this case, right?
> 
> https://github.com/Grandthrax/yearnV2-generic-lender-strat/blob/8488418e61fe21fba15187e0799d94531ed5cf8f/contracts/Strategy.sol#L346

you are right. Why did I include that? Lol... hmmm

**Comment by Grandthrax** [comment]
> Suggestion(medium):
> 
> Can expose in the GenericLender interface the strategy variable so it can be checked against when adding
> here as an additional validation to avoid docking incorrect lenders
> 
> https://github.com/Grandthrax/yearnV2-generic-lender-strat/blob/8488418e61fe21fba15187e0799d94531ed5cf8f/contracts/Strategy.sol#L66
> 
> ```
> require(n.strategy() == address(this)..);
> ```

good idea

**Comment by Grandthrax** [comment]
> > Comment (Minor):
> > I think `_loss` always going to be 0 for this case, right?
> > https://github.com/Grandthrax/yearnV2-generic-lender-strat/blob/8488418e61fe21fba15187e0799d94531ed5cf8f/contracts/Strategy.sol#L346
> 
> you are right. Why did I include that? Lol... hmmm

Turns out this was a mistake! Should be:

_debtPayment = Math.min(newLoose - _profit, _debtPayment);

Good spot. That could have caused some future problem!

**Comment by Grandthrax** [comment]
various fixes: [5659e4996251383c0198a6ca3c1084a6ef58c758](https://github.com/Grandthrax/yearnV2-generic-lender-strat/commit/5659e4996251383c0198a6ca3c1084a6ef58c758)

**Comment by dmolina79** [comment]
Comment:(Low)

For precision here we could use existing `nav()` function to check against dust right?

https://github.com/Grandthrax/yearnV2-generic-lender-strat/blob/8488418e61fe21fba15187e0799d94531ed5cf8f/contracts/GenericLender/AlphaHomoLender.sol#L187

**Comment by dmolina79** [comment]
Comment (Low):

In both interactions of withdrawing from Alpha since we receive native ETH back the `withdrawn` amount may be assumed to be from Alpha, where in fact could be residual eth on the contract left by somebody sending to ETH to contract.

At first glance not able to tell if it can affect any calculation in a bad way, since like it would count as a donation given the flow, right?

**Comment by dougstorm** [comment]
closing issue since audit came back with no major issues
