### ISSUE TITLE
USDC: Idle Finance 

### ISSUE THREAD

**Issue by dmolina79** [iearn-finance/yearn-strategies#6]
Description: Emiliano's Strategy using USDC and IDLE.

Initial Review Commit: [98a29e97ec4c98d879437f6368b99deb843b80c2](https://github.com/emilianobonassi/yIdleStrategies/commit/98a29e97ec4c98d879437f6368b99deb843b80c2)

Latest Review Commit: [7cc52109e672105d9a1c8dccf8ec46e39982c312](https://github.com/emilianobonassi/yIdleStrategies/commit/7cc52109e672105d9a1c8dccf8ec46e39982c312)

Repo: [issues](https://github.com/emilianobonassi/yIdleStrategies/issues)

Review Ongoing By:

- [x] Doug
- [x] Grandthrax

Review Completed By:

- [x] Doug
- [x] Grandthrax

**Comment by dmolina79** [comment]
It would be good to have a check for require that asserts the strategy is working with the intended want

` address constant public _want = address(0x0001);`
...

```
constructor(
    address _vault
  )
 require(want(address) == vault(_vault).want());
```

**Comment by dmolina79** [comment]
Comment:

https://github.com/emilianobonassi/yIdleStrategies/blob/98a29e97ec4c98d879437f6368b99deb843b80c2/contracts/StrategyIdle.sol#L203

Here this line read of virtual price could be replaced to use stored value via modifier?
So:
`uint256 currentVirtualPrice = IIdleTokenV3_1(idleYieldToken).tokenPrice();`

is equal to:
`uint256 currentVirtualPrice = lastVirtualPrice;`

Saving some gas?

**Comment by dmolina79** [comment]
Comment:

Does this swap work in testing?
https://github.com/iearn-finance/yearn-strategies/issues/6

```
  IUniswapRouter(uniswapRouterV2).swapExactTokensForTokens(
                compBalance, 1, uniswapCompPath, address(this), block.timestamp
            );
```

Usually transactions get more reverts when given exact timestamp and in other strats i see we use as buffer 1800
see: 

https://github.com/iearn-finance/yearn-protocol/blob/2252c4f1f2af464dbf066da8e41a57498e4f6330/contracts/strategies/StrategyCurvemUSDVoterProxy.sol#L182

Uniswap UI uses 3000 i believe

**Comment by dmolina79** [comment]
Question:

I see the comment but still don't understand why redeem is called with 0 amount here, is there a side effect on their token that needs to happen?

https://github.com/emilianobonassi/yIdleStrategies/blob/98a29e97ec4c98d879437f6368b99deb843b80c2/contracts/StrategyIdle.sol#L127

I walked through the code and they do work with the amount so was wondering.

**Comment by dmolina79** [comment]
Comment:
At the time of the review the idleToken is pointing to this contract which is upgradable so on future upgrades some assumptions may change:
https://etherscan.io/address/0x5274891bEC421B39D23760c04A6755eCB444797C#readProxyContract

**Comment by dmolina79** [comment]
Comment:

Is it possible to check or assert that the requested `valueToRedeem` from side effect was actually credit to contract balance in the line below?

https://github.com/emilianobonassi/yIdleStrategies/blob/98a29e97ec4c98d879437f6368b99deb843b80c2/contracts/StrategyIdle.sol#L212

**Comment by emilianobonassi** [comment]
> Suggestion: (Not Critical)
> 
> It would be good to have a check for require that asserts the strategy is working with the intended want
> 
> ` address constant public _want = address(0x0001);`
> ...
> 
> https://github.com/emilianobonassi/yIdleStrategies/blob/98a29e97ec4c98d879437f6368b99deb843b80c2/contracts/StrategyIdleUSDC_BY.sol#L28
> 
> ```
> constructor(
>     address _vault
>   )
>  require(address(_want) == address(want));
> ```

Good suggestion, it prevents to spawn a wrong strategy and go in the same direction as the latest fix on the vaults.

Will do.

**Comment by emilianobonassi** [comment]
> Comment:
> 
> https://github.com/emilianobonassi/yIdleStrategies/blob/98a29e97ec4c98d879437f6368b99deb843b80c2/contracts/StrategyIdle.sol#L203
> 
> Here this line read of virtual price could be replaced to use stored value via modifier side effect, right?
> So:
> `uint256 currentVirtualPrice = IIdleTokenV3_1(idleYieldToken).tokenPrice();`
> 
> is equal to:
> `uint256 currentVirtualPrice = lastVirtualPrice;`
> 
> Saving some gas?

This is a good catch. Let me check everything works and add this too. The keeper will spend less. In this case, I will add too.

**Comment by emilianobonassi** [comment]
> Comment:
> 
> Does these swap work well in live testing?
> 
> https://github.com/emilianobonassi/yIdleStrategies/blob/98a29e97ec4c98d879437f6368b99deb843b80c2/contracts/StrategyIdle.sol#L280
> 
> https://github.com/emilianobonassi/yIdleStrategies/blob/98a29e97ec4c98d879437f6368b99deb843b80c2/contracts/StrategyIdle.sol#L292
> 
> ```
>   IUniswapRouter(uniswapRouterV2).swapExactTokensForTokens(
>                 compBalance, 1, uniswapCompPath, address(this), block.timestamp
>             );
> ```
> 
> Usually transactions get more reverts when given exact timestamp as deadline and in other strats i see we use as buffer deadline 1800
> see:
> 
> https://github.com/iearn-finance/yearn-protocol/blob/2252c4f1f2af464dbf066da8e41a57498e4f6330/contracts/strategies/StrategyCurvemUSDVoterProxy.sol#L182
> 
> Uniswap UI uses 3000 i believe

The second `harvest()` which liquidated on Uniswap worked pretty well

https://etherscan.io/tx/0xceb0670121efbdde8216e8c557488f039f6d19aaad58089832e6d836f6916620

Anyway, if you already use that buffer I prefer to go in that direction. I will add too.

**Comment by emilianobonassi** [comment]
> Question:
> 
> I see the comment but still don't understand why redeem is called with 0 amount here, is there a side effect on their token that needs to happen?
> 
> https://github.com/emilianobonassi/yIdleStrategies/blob/98a29e97ec4c98d879437f6368b99deb843b80c2/contracts/StrategyIdle.sol#L127
> 
> I walked through the code and they do work with the amount so was wondering.

The reason is that there are some cases, `_debtOutstanding == 0`, when we don't redeem so we don't claim the IDLE and COMP rewards. This means that we wouldn't have anything to liquidate also if there should be.

Redeeming 0 will allow us to stay in Idle but claiming IDLE and COMP, since every redeem always claim IDLE and COMP.

We could argue to find a method to avoid a double claim in the case we already claimed here 

https://github.com/emilianobonassi/yIdleStrategies/blob/98a29e97ec4c98d879437f6368b99deb843b80c2/contracts/StrategyIdle.sol#L120

https://github.com/emilianobonassi/yIdleStrategies/blob/98a29e97ec4c98d879437f6368b99deb843b80c2/contracts/StrategyIdle.sol#L212

I could use a simple state which we reset on a successfull redeem e.g. 

1. At the beginning `prepareReturn()` set `redeemed = false`
2. In the liquidate if `redeemIdleToken` is called set it to true
3. Don't repeat `redeemIdleToken` in `prepareReturn()` if it is set to true and set it to false

We should do a comparison if we save gas instead of call `redeemIdleToken` twice (probably yes).

What do you think @dmolina79 ?

**Comment by emilianobonassi** [comment]
> Comment:
> At the time of the review the idleToken is pointing to this contract which is upgradable so on future upgrades some assumptions made in this review may change:
> https://etherscan.io/address/0x5274891bEC421B39D23760c04A6755eCB444797C#readProxyContract

Yes, it's correct.

Consider that the proxy are governed by the IDLE governance via the proxyAdmin https://etherscan.io/address/0x7740792812a00510b50022d84e5c4ac390e01417 owned by the Timelock https://etherscan.io/address/0xd6dabbc2b275114a2366555d6c481ef08fdc2556#code

IDLE implement a governance a-la Compound, you have 3 days for voting and 2 days before executing

We could track using HAL or other ways when a new voting is gonna to happen and react accordingly in the case is going to change the impl.

**Comment by emilianobonassi** [comment]
> Comment:
> 
> Is it possible to check or assert that the requested `valueToRedeem` from side effect was actually credit to contract balance in the line below?
> 
> https://github.com/emilianobonassi/yIdleStrategies/blob/98a29e97ec4c98d879437f6368b99deb843b80c2/contracts/StrategyIdle.sol#L212

Good catch. I will add a balance check pre and post with the diff require.

**Comment by emilianobonassi** [comment]
> > Suggestion: (Not Critical)
> > It would be good to have a check for require that asserts the strategy is working with the intended want
> > ` address constant public _want = address(0x0001);`
> > ...
> > https://github.com/emilianobonassi/yIdleStrategies/blob/98a29e97ec4c98d879437f6368b99deb843b80c2/contracts/StrategyIdleUSDC_BY.sol#L28
> > ```
> > constructor(
> >     address _vault
> >   )
> >  require(address(_want) == address(want));
> > ```
> 
> Good suggestion, it prevents to spawn a wrong strategy and go in the same direction as the latest fix on the vaults.
> 
> Will do.

@dmolina79 done

https://github.com/emilianobonassi/yIdleStrategies/commit/04a09d21772490992ef06227686cecfdef0235dd

You can run previous commit to check test fails 💪

**Comment by emilianobonassi** [comment]
> lastVirtualPrice

@dmolina79 done

https://github.com/emilianobonassi/yIdleStrategies/commit/0f7c5767b7a2c3d09790dfb35a6eebf604eb66b2

**Comment by emilianobonassi** [comment]
> https://github.com/iearn-finance/yearn-protocol/blob/2252c4f1f2af464dbf066da8e41a57498e4f6330/contracts/strategies/StrategyCurvemUSDVoterProxy.sol#L182

@dmolina79 done

https://github.com/emilianobonassi/yIdleStrategies/commit/f7072a2c416e6237d240a0f111ff4b4645ef1bb1

**Comment by emilianobonassi** [comment]
> 1. redeemed = false

@dmolina79 done

https://github.com/emilianobonassi/yIdleStrategies/commit/f38c942f760dda4221972a52919b836ebb5d9249

**Comment by dmolina79** [comment]
> > 1. redeemed = false
> 
> @dmolina79 done
> 
> [emilianobonassi/yIdleStrategies@f38c942](https://github.com/emilianobonassi/yIdleStrategies/commit/f38c942f760dda4221972a52919b836ebb5d9249)

Left a comment here:
https://github.com/emilianobonassi/yIdleStrategies/commit/f38c942f760dda4221972a52919b836ebb5d9249#r45054071

Not sure we gain much by adding the condition logic, and honestly if it doesnt affect the complete flow of your strategy i would vote to simplify it, if its just an optimization i suggest in favor of simple code over optimized.

WDYT?

**Comment by emilianobonassi** [comment]
> > Comment:
> > Is it possible to check or assert that the requested `valueToRedeem` from side effect was actually credit to contract balance in the line below?
> > https://github.com/emilianobonassi/yIdleStrategies/blob/98a29e97ec4c98d879437f6368b99deb843b80c2/contracts/StrategyIdle.sol#L212
> 
> Good catch. I will add a balance check pre and post with the diff require.

@dmolina79 done

https://github.com/emilianobonassi/yIdleStrategies/commit/e7915c4504779f9744e68c6cd7e4aeb99bda641e

**Comment by emilianobonassi** [comment]
> > > 1. redeemed = false
> > 
> > 
> > @dmolina79 done
> > [emilianobonassi/yIdleStrategies@f38c942](https://github.com/emilianobonassi/yIdleStrategies/commit/f38c942f760dda4221972a52919b836ebb5d9249)
> 
> Left a comment here:
> [emilianobonassi/yIdleStrategies@f38c942#r45054071](https://github.com/emilianobonassi/yIdleStrategies/commit/f38c942f760dda4221972a52919b836ebb5d9249#r45054071)
> 
> Not sure we gain much by adding the condition logic, and honestly if it doesnt affect the complete flow of your strategy i would vote to simplify it, if its just an optimization i suggest in favor of simple code over optimized.
> 
> If the claim(0) line does not affect the overall logic, im good to keep it as is before this change.
> 
> WDYT?

It doesn't but could be an optimization to avoid double computation on the redeem

I've explained more extensively here 

https://github.com/emilianobonassi/yIdleStrategies/commit/f38c942f760dda4221972a52919b836ebb5d9249#commitcomment-45054321

If you need further info, please catch up on tg, we could do a quick call ;)

**Comment by emilianobonassi** [comment]
@dmolina79 latest commit to review is https://github.com/emilianobonassi/yIdleStrategies/commit/65e9e788dd68db08e6af31146d85015d8e2d1653

Introduced:
- configurability of check on redeemed amount to granular check on emergency issues
- break the glass helpers enable/disable all checks 
- generalized for multiple gov tokens (along to comp and idle) for further upgrades of Idle (e.g. add another yield provider which farm a token different than COMP)

Looking for your final review and the launch!

**Comment by emilianobonassi** [comment]
The only surface of attack introduced by the latest improvement is that governance could set to empty the gov tokens, harvest and withdraw them but I think the security assumption is that gov is trusted party.

In the case I could have a list which is add only so in the worst case of errors we should migrate the strat. It's up to us. Let me know what you think 😉

Thank a lot in advance.

**Comment by Grandthrax** [comment]
Nice strat!
Haven't had time to look through in detail. One thing that jumped out:

If liquidate position returns more than the amount requested it breaks vault accounting. Use Math.min(balanceOfWant(), _amountNeeded)

**Comment by dmolina79** [comment]
> The only surface of attack introduced by the latest improvement is that governance could set to empty the gov tokens, harvest and withdraw them but I think the security assumption is that gov is trusted party.
> 
> In the case I could have a list which is add only so in the worst case of errors we should migrate the strat. It's up to us. Let me know what you think 😉
> 
> Thank a lot in advance.

Correct, yearn governance being a trusted actor is an assumption for all vault/strats

**Comment by dmolina79** [comment]
> Nice strat!
> Haven't had time to look through in detail. One thing that jumped out:
> 
> If liquidate position returns more than the amount requested it breaks vault accounting. Use Math.min(balanceOfWant(), _amountNeeded)

Good point, 
https://github.com/emilianobonassi/yIdleStrategies/blob/f38c942f760dda4221972a52919b836ebb5d9249/contracts/StrategyIdle.sol#L226

On this line should be the min between the two in the return 
`Use Math.min(balanceOfWant(), _amountNeeded)`

**Comment by emilianobonassi** [comment]
Thanks @Grandthrax , good catch!

Thanks @dmolina79 for the follow-up!

Fixed in the latest commit https://github.com/emilianobonassi/yIdleStrategies/commit/7cc52109e672105d9a1c8dccf8ec46e39982c312

I will keep a note to add it in the mocked tests 👍

**Comment by dmolina79** [comment]
Changes on latest commit LGTM, when new tests are in lmk so i can update the hash for review

**Comment by dmolina79** [comment]
Im closing this issue as reviewed to do housekeeping, we can reopen if we feel is still needed
